import React from 'react';
import { createRoot } from 'react-dom/client';
import { Car, Users, Calendar, Wallet, Fuel, MessageCircle, BarChart3, Settings, LogOut, MapPin, Clock, Send, ShieldCheck, Truck, Menu } from 'lucide-react';
import './styles.css';

const blue = '#071b4d';
const red = '#ef233c';

const trips = [
  ['TRIP-001','06:30','Sarah Khan','Michael Brown','Azizi Riviera → Business Bay','In Progress','150 AED'],
  ['TRIP-002','09:15','John Smith','Ali Hassan','Business Bay → JLT','Scheduled','180 AED'],
  ['TRIP-003','13:30','Emily Davis','Saeed Khan','JLT → DIFC','Scheduled','120 AED'],
];
const drivers = [['Michael Brown','On Duty','Toyota Coaster BUS101','3,250 AED'],['Ali Hassan','Available','Toyota Hiace BUS102','1,850 AED'],['Saeed Khan','Off Duty','Nissan Urvan BUS103','2,100 AED']];
const passengers = [['Sarah Khan','+1,250 AED','Active trip'],['John Smith','-50 AED','Payment pending'],['Emily Davis','450 AED','Recurring trip']];

function Logo(){return <div className="logo"><span>LETS</span><b>DRIVE</b></div>}
function Sidebar({role='admin'}){const items= role==='driver' ? [['Dashboard',Car],['My Trips',Calendar],['Passengers',Users],['Fuel Records',Fuel],['Messages',MessageCircle],['My Balance',Wallet],['Logout',LogOut]] : [['Dashboard',BarChart3],['Trip Management',Calendar],['Drivers',Car],['Passengers',Users],['Vehicles',Truck],['Payments',Wallet],['Fuel Records',Fuel],['Reports',BarChart3],['Settings',Settings]];return <aside className="sidebar"><Logo/><div className="profile"><div className="avatar">MB</div><div><b>{role==='driver'?'Michael Brown':'Admin User'}</b><small>{role==='driver'?'Driver':'Administrator'}</small></div></div>{items.map(([t,I],i)=><div className={'nav '+(i===0?'active':'')} key={t}><I size={18}/>{t}</div>)}</aside>}
function Shell({children,role}){return <div className="app"><Sidebar role={role}/><main><header><Menu/><input placeholder="Search anything..."/><div className="pill">English</div></header>{children}</main></div>}
function Stat({title,value,icon}){return <div className="stat"><div className="icon">{icon}</div><small>{title}</small><h2>{value}</h2></div>}
function AdminDashboard(){return <Shell><h1>Dashboard</h1><p className="muted">Today’s operations overview.</p><div className="grid4"><Stat title="Today’s Trips" value="18" icon="📅"/><Stat title="Completed" value="11" icon="✅"/><Stat title="Daily Revenue" value="5,420 AED" icon="💳"/><Stat title="Active Drivers" value="7" icon="🚘"/></div><section className="card"><h2>Ongoing Trips</h2><table><thead><tr><th>Trip</th><th>Time</th><th>Passenger</th><th>Driver</th><th>Route</th><th>Status</th><th>Fare</th></tr></thead><tbody>{trips.map(r=><tr>{r.map((c,i)=><td><span className={i===5?'badge':''}>{c}</span></td>)}</tr>)}</tbody></table></section><div className="grid3"><Mini title="Drivers" rows={drivers}/><Mini title="Passengers" rows={passengers}/><Mini title="Quick Actions" rows={[['Assign Trip','Create a new trip'],['Recurring Trips','Templates'],['Reports','Export data']]}/></div></Shell>}
function Mini({title,rows}){return <section className="card"><h2>{title}</h2>{rows.map((r)=><div className="line"><b>{r[0]}</b><span>{r[1]}</span><small>{r[2]||r[3]||''}</small></div>)}</section>}
function DriverLogin(){return <div className="login"><Logo/><div className="login-card"><div className="driver-icon">👨‍✈️</div><h1>Driver Login</h1><p>Welcome back! Please login to continue.</p><label>Username</label><input placeholder="Enter your username"/><label>Password</label><input type="password" placeholder="Enter your password"/><a>Forgot Password?</a><button onClick={()=>location.href='/driver'}>Login</button><p>Need help? <b>Contact support</b></p></div><footer>© 2024 LetsDrive. Version 1.0.0</footer></div>}
function DriverDashboard(){return <Shell role="driver"><h1>Good Morning, Michael 👋</h1><p className="muted">Have a safe and productive day.</p><section className="card vehicle"><img src="https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=300"/><div><h2>Toyota Coaster</h2><b>BUS101</b></div><Stat title="Shift Started" value="06:25 AM" icon="🕘"/><Stat title="Current KM" value="125,576" icon="🧾"/></section><div className="grid4"><Stat title="Trips" value="5" icon="📅"/><Stat title="Passengers" value="82" icon="👥"/><Stat title="Distance" value="126 KM" icon="📍"/><Stat title="Collections" value="1,250 AED" icon="💳"/></div><div className="grid2"><section className="card"><h2>Current Trip</h2><p><MapPin/> Azizi Riviera → Business Bay</p><p><Clock/> Est. 08:55 AM</p><button className="danger">End Trip</button><button>Open in Waze</button></section><section className="card"><h2>Message Passenger</h2><div className="chat"><p className="bubble">I’m on the way.</p><p className="bubble right">Thank you!</p></div><div className="send"><input placeholder="Type message..."/><button><Send size={18}/></button></div><small>You can only message passengers assigned to active trips.</small></section></div><section className="card balance"><h2>My Balance</h2><h1>3,250 AED</h1><div className="grid4"><Stat title="Today Earned" value="150 AED" icon="💵"/><Stat title="This Month" value="3,600 AED" icon="📆"/><Stat title="Paid Leaves" value="2" icon="✅"/><Stat title="Unpaid Leave" value="1" icon="⛔"/></div></section></Shell>}
function PassengerTrip(){return <div className="passenger"><Logo/><div className="top"><h1>Good Morning, Sarah 👋</h1><span className="status">● Trip In Progress</span></div><section className="card route"><div><b>Pickup</b><h2>Azizi Riviera</h2><small>06:30 AM</small></div><div className="carcircle">🚘</div><div><b>Drop-off</b><h2>Business Bay</h2><small>Est. 08:55 AM</small></div></section><section className="card driver"><div className="avatar big">MB</div><div><h2>Michael Brown ⭐ 4.9</h2><button>Message Driver</button></div><img src="https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=240"/><div><h2>Toyota Coaster</h2><b>BUS101</b><p>Plate 12345</p></div></section><section className="map"><div className="pin start">Your Location<br/>Azizi Riviera</div><div className="road"></div><div className="bus">🚌</div><div className="pin end">Drop-off<br/>Business Bay</div></section><div className="grid4"><Stat title="Estimated Arrival" value="06:35 AM" icon="🕘"/><Stat title="Distance Remaining" value="3.2 km" icon="📍"/><Stat title="Driver Speed" value="42 km/h" icon="⚙️"/><Stat title="Total Distance" value="8.7 km" icon="〰️"/></div><section className="card"><h2>Send a Message</h2><div className="send"><input placeholder="Type your message..."/><button><Send size={18}/></button></div><small>Your message will be seen by the driver in the driver panel.</small></section><div className="grid2"><section className="card"><h2>Your Balance</h2><h1>1,250 AED</h1></section><section className="card"><h2>Make a Payment</h2><p>Send payment notification</p></section></div><p className="secure"><ShieldCheck/> Only you can access this page. Please do not share this link.</p></div>}
function PassengerBalance(){return <div className="passenger"><Logo/><h1>My Balance</h1><section className="card balance"><h1>1,250 AED</h1><p>Last updated today 06:25 AM</p></section><section className="card"><h2>Payment Notification</h2><input placeholder="Amount paid (AED)"/><input placeholder="Reference number"/><input type="file"/><button>Submit Payment</button><p className="promo">Pay extra and receive 10% bonus credit on the amount remaining after clearing your balance.</p></section></div>}
function App(){const path=location.pathname;if(path.startsWith('/driver-login'))return <DriverLogin/>;if(path.startsWith('/driver'))return <DriverDashboard/>;if(path.startsWith('/t/'))return <PassengerTrip/>;if(path.startsWith('/b/'))return <PassengerBalance/>;return <AdminDashboard/>}
createRoot(document.getElementById('root')).render(<App/>);
